openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs Executions
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobs/{jobId}/executions/_count:
    post:
      tags:
        - Job - Execution
      summary: Count the Jobs Executions
      operationId: jobExecutionCount
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
      requestBody:
        $ref: '../openapi.yaml#/components/requestBodies/kapuaQuery'
      responses:
        200:
          $ref: '../openapi.yaml#/components/responses/countResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
