openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs - Executions
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobs/{jobId}/executions/{executionId}/targets:
    get:
      tags:
        - Job - Execution
      summary: Get all the targets involved in a single Job Execution
      operationId: jobExecutionListTarget
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
        - $ref: './jobExecution.yaml#/components/parameters/executionId'
      responses:
        200:
          description: The list of the targets involved in a single Job Execution
          content:
            application/json:
              schema:
                $ref: '../jobTarget/jobTarget.yaml#/components/schemas/jobTargetListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
