openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs Executions
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobs/{jobId}/executions:
    get:
      tags:
        - Job - Execution
      summary: Get all the Jobs Executions
      operationId: jobExecutionList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
        - $ref: '../openapi.yaml#/components/parameters/sortParam'
        - $ref: '../openapi.yaml#/components/parameters/sortDir'
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
        - $ref: '../openapi.yaml#/components/parameters/askTotalCount'
      responses:
        200:
          description: The list of the Jobs available in the Scope
          content:
            application/json:
              schema:
                $ref: './jobExecution.yaml#/components/schemas/jobExecutionListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
