openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobs/{jobId}:
    get:
      tags:
        - Job
      summary: Get a single Job
      operationId: jobGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './job.yaml#/components/parameters/jobId'
      responses:
        200:
          description: The details of the desired Job
          content:
            application/json:
              schema:
                $ref: './job.yaml#/components/schemas/job'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    put:
      tags:
        - Job
      summary: Update a single Job
      operationId: jobUpdate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './job.yaml#/components/parameters/jobId'
      requestBody:
        description: An object containing the new properties for the Job to update
        content:
          application/json:
            schema:
              $ref: './job.yaml#/components/schemas/job'
            example:
              type: job
              optlock: 1
        required: true
      responses:
        200:
          description: The details of the updated Job
          content:
            application/json:
              schema:
                $ref: './job.yaml#/components/schemas/job'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - Job
      summary: Delete a single Job
      operationId: jobDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './job.yaml#/components/parameters/jobId'
        - name: forced
          in: query
          description: Delete the Job forcibly. It can only be used by the system administrator.
          schema:
            type: boolean
            default: false
      responses:
        204:
          description: The Job has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
