openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Accounts
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/accounts/_query:
    post:
      tags:
        - Account
      summary: Query the Accounts
      operationId: accountQuery
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        $ref: '../openapi.yaml#/components/requestBodies/kapuaQuery'
      responses:
        200:
          description: The result of the query
          content:
            application/json:
              schema:
                $ref: './account.yaml#/components/schemas/accountListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
      description: Returns a list of the Accounts matching the given query in the Scope. Predicates are not currently supported.
