openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Accounts
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/accounts/_count:
    post:
      tags:
        - Account
      summary: Count the Accounts
      operationId: accountCount
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        $ref: '../openapi.yaml#/components/requestBodies/kapuaQuery'
      responses:
        200:
          $ref: '../openapi.yaml#/components/responses/countResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
      description: Returns the count of how many Accounts are present in the given Scope
