openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Authentication
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /authentication/user:
    post:
      tags:
        - Authentication
      summary: Login - User and Password
      operationId: authenticationUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'authentication.yaml#/components/schemas/usernamePasswordCredentials'
            required: true
            examples:
              Admin:
                value:
                  username: kapua-sys
                  password: kapua-password
              MFA with AuthenticationCode:
                value:
                  username: kapua-sys
                  password: kapua-password
                  authenticationCode: 123456
                  trustMe: true
              MFA with TrustKey:
                value:
                  username: kapua-sys
                  password: kapua-password
                  trustKey: 4bba9938-aa8f-11ec-b909-0242ac120002
      responses:
        200:
          description: The new AccessToken
          content:
            application/json:
              schema:
                $ref: './authentication.yaml#/components/schemas/accessToken'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
      security: []
