openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Data Metric
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/data/metrics/{metricInfoId}:
    get:
      tags:
        - Data Metric
      summary: Get a single MetricInfo
      operationId: metricInfoGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './dataMetric.yaml#/components/parameters/metricInfoId'
      responses:
        200:
          description: The desired MetricInfo
          content:
            application/json:
              schema:
                $ref: './dataMetric.yaml#/components/schemas/metricInfo'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
