version: '3.1'

services:
  message-broker:
    ports:
      - ${KAPUA_BROKER_DEBUG_PORT:-5005}:5005
    environment:
      - ACTIVEMQ_DEBUG_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=${KAPUA_BROKER_DEBUG_SUSPEND:-n},address=5005