version: '3.1'

services:
  consumer-lifecycle:
    ports:
      - ${KAPUA_CONSUMER_LIFECYCLE_DEBUG_PORT:-8002}:8001
    environment:
      - DEBUG_OPTIONS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=${KAPUA_CONSUMER_LIFECYCLE_DEBUG_SUSPEND:-n},address=8001