openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs Steps
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  parameters:
    stepId:
      name: stepId
      in: path
      description: The ID of the Job Step on which to perform the operation
      schema:
        $ref: '../openapi.yaml#/components/schemas/kapuaId'
      required: true
  schemas:
    jobStep:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntity'
        - type: object
          example:
            type: jobStep
            id: BL2MaF-ldS0
            scopeId: AQ
            createdOn: '2019-12-06T11:00:21.000Z'
            createdBy: AQ
            modifiedOn: '2019-12-06T11:00:21.000Z'
            modifiedBy: AQ
            optlock: 1
            name: step_one
            jobId: auSoU2ph1bY
            jobStepDefinitionId: Cg
            stepIndex: 0
            stepProperties:
              - name: commandInput
                propertyType: org.eclipse.kapua.service.device.management.command.DeviceCommandInput
                propertyValue: |-
                  <?xml version="1.0" encoding="UTF-8"?>
                   <commandInput>
                      <command>ls</command>
                      <timeout>30000</timeout>
                      <runAsynch>false</runAsynch>
                   </commandInput>
              - name: timeout
                propertyType: java.lang.Long
    jobStepCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaUpdatableEntityCreator'
        - type: object
          properties:
            stepIndex:
              type: number
            jobStepDefinitionId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            jobStepProperties:
              type: array
              items:
                $ref: '../jobStepDefinition/jobStepDefinition.yaml#/components/schemas/jobStepDefinitionProperty'
      example:
        type: jobStepCreator
        name: Step 1
        description: A step with a description
        stepIndex: 0
        jobStepDefinitionId: Aw
        jobStepProperties:
          - name: bundleId
            propertyType: java.lang.String
            propertyValue: '999'
    jobStepListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/jobStep'
          example:
            type: jobStepListResult
            limitExceeded: false
            size: 1
            items:
              - type: jobStep
                id: BL2MaF-ldS0
                scopeId: AQ
                createdOn: '2019-12-06T11:00:21.000Z'
                createdBy: AQ
                modifiedOn: '2019-12-06T11:00:21.000Z'
                modifiedBy: AQ
                optlock: 1
                name: step_one
                jobId: auSoU2ph1bY
                jobStepDefinitionId: Cg
                stepIndex: 0
                stepProperties:
                  - name: commandInput
                    propertyType: org.eclipse.kapua.service.device.management.command.DeviceCommandInput
                    propertyValue: |-
                      <?xml version="1.0" encoding="UTF-8"?>
                       <commandInput>
                          <command>ls</command>
                          <timeout>30000</timeout>
                          <runAsynch>false</runAsynch>
                       </commandInput>
                  - name: timeout
                    propertyType: java.lang.Long
