openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs - Trigger Fired
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: { }

components:
  parameters:
    triggerId:
      name: triggerId
      in: path
      description: The ID of the Job Trigger on which to perform the operation
      schema:
        $ref: '../openapi.yaml#/components/schemas/kapuaId'
      required: true
  schemas:
    firedTrigger:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaEntity'
        - type: object
          example:
            type: firedTrigger
            id: OlIPEFS4MYU
            scopeId: AQ
            createdOn: '2019-12-06T11:01:16.000Z'
            createdBy: AQ
            firedOn: '2019-12-07T01:30:00+01:00'
            message: 'A error message'
            status:
              $ref: './jobTriggerFired.yaml#/components/schemas/firedTriggerStatus'
            triggerId:
              $ref: './jobTriggerFired.yaml#/components/parameters/triggerId'
    firedTriggerListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/firedTrigger'
          example:
            - type: triggerListResult
              limitExceeded: false
              size: 3
              items:
                - type: firedTrigger
                  id: OlIPEFS4MYU
                  scopeId: AQ
                  createdOn: '2019-12-06T11:03:16.000Z'
                  createdBy: AQ
                  firedOn: '2019-12-06T11:03:16.000Z'
                  message: 'A error message'
                  status: 'FAILED'
                  triggerId: auSoU2ph1bY
                - type: firedTrigger
                  id: OlIPEFS4MYU
                  scopeId: AQ
                  createdOn: '2019-12-06T11:02:16.000Z'
                  createdBy: AQ
                  firedOn: '2019-12-06T11:02:16.000Z'
                  status: 'FIRED'
                  triggerId: auSoU2ph1bY
                - type: firedTrigger
                  id: OlIPEFS4MYU
                  scopeId: AQ
                  createdOn: '2019-12-06T11:01:16.000Z'
                  createdBy: AQ
                  firedOn: '2019-12-06T11:01:16.000Z'
                  status: 'FIRED'
                  triggerId: auSoU2ph1bY
    firedTriggerStatus:
      type: string
      enum:
        - FIRED
        - FAILED
