openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Data Client
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/data/clients/{clientInfoId}:
    get:
      tags:
        - Data Client
      summary: Get a single ClientInfo
      operationId: clientInfoGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './dataClient.yaml#/components/parameters/clientInfoId'
      responses:
        200:
          description: The desired ClientInfo
          content:
            application/json:
              schema:
                $ref: './dataClient.yaml#/components/schemas/clientInfo'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
