openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Data Client
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/data/clients:
    get:
      tags:
        - Data Client
      summary: Query the Data Clients
      operationId: dataClientQuery
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - name: clientId
          in: query
          schema:
            type: string
          description: The ClientID to filter results
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
      responses:
        200:
          description: The result of the query
          content:
            application/json:
              schema:
                $ref: './dataClient.yaml#/components/schemas/clientInfoListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
