openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Tags
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/tags/{tagId}:
    get:
      tags:
        - Tag
      summary: Get a single Tag
      operationId: tagGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './tag.yaml#/components/parameters/tagId'
      responses:
        200:
          description: The details of the desired Tag
          content:
            application/json:
              schema:
                $ref: './tag.yaml#/components/schemas/tag'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    put:
      tags:
        - Tag
      summary: Update a single Tag
      operationId: tagUpdate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './tag.yaml#/components/parameters/tagId'
      requestBody:
        description: An object containing the new properties for the Tag to update
        content:
          application/json:
            schema:
              $ref: './tag.yaml#/components/schemas/tag'
            example:
              optlock: 1
              name: new-tag
              description: A new Description for a new Tag
        required: true
      responses:
        200:
          description: The details of the updated Tag
          content:
            application/json:
              schema:
                $ref: './tag.yaml#/components/schemas/tag'
              example:
                type: tag
                id: FJ6-FLuIcok
                scopeId: AQ
                createdOn: '2019-09-16T08:52:32.562Z'
                createdBy: AQ
                modifiedOn: '2019-09-16T08:55:43.719Z'
                modifiedBy: AQ
                optlock: 2
                name: new-tag
                description: A new Description for a new Tag
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - Tag
      summary: Delete a single Tag
      operationId: tagDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './tag.yaml#/components/parameters/tagId'
      responses:
        204:
          description: The Tag has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
