openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs Step Definitions
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobStepDefinitions/_query:
    post:
      tags:
        - Job - Step Definition
      summary: Query the Jobs Step Definitions
      operationId: jobStepDefinitionQuery
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        $ref: '../openapi.yaml#/components/requestBodies/kapuaQuery'
      responses:
        200:
          description: The result of the query
          content:
            application/json:
              schema:
                $ref: './jobStepDefinition.yaml#/components/schemas/jobStepDefinitionListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
