openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs - Step Definitions
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobStepDefinitions/{jobStepDefinitionId}:
    get:
      tags:
        - Job - Step Definition
      summary: Get a single Job Step Definition
      operationId: jobStepDefinitionGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './jobStepDefinition.yaml#/components/parameters/jobStepDefinitionId'
      responses:
        200:
          description: The details of the desired Job Step Definition
          content:
            application/json:
              schema:
                $ref: './jobStepDefinition.yaml#/components/schemas/jobStepDefinition'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
