openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - RolePermissions
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/roles/{roleId}/permissions/{permissionId}:
    get:
      tags:
        - Role
      summary: Get a single RolePermission
      operationId: rolePermissionGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './role.yaml#/components/parameters/roleId'
        - $ref: './role.yaml#/components/parameters/rolePermissionId'
      responses:
        200:
          description: The details of the desired RolePermission
          content:
            application/json:
              schema:
                $ref: './role.yaml#/components/schemas/rolePermission'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - Role
      summary: Delete a single RolePermission
      operationId: rolePermissionDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './role.yaml#/components/parameters/roleId'
        - $ref: './role.yaml#/components/parameters/rolePermissionId'
      responses:
        204:
          description: The RolePermission has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
