openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Roles
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/roles/{roleId}/users:
    get:
      tags:
        - Role
      summary: Get all the Users for the given Role
      operationId: roleListUsers
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './role.yaml#/components/parameters/roleId'
        - $ref: '../openapi.yaml#/components/parameters/sortParam'
        - $ref: '../openapi.yaml#/components/parameters/sortDir'
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
      responses:
        200:
          description: The list of the Users assigned to the given Role
          content:
            application/json:
              schema:
                $ref: '../user/user.yaml#/components/schemas/userListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
