openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Users
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  parameters:
    userId:
      name: userId
      in: path
      description: The ID of the User on which to perform the operation
      schema:
        $ref: '../openapi.yaml#/components/schemas/kapuaId'
      required: true
  schemas:
    user:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntity'
        - $ref: '#/components/schemas/userCreator'
        - type: object
          example:
            $ref: '#/components/examples/user/value'
    userCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntityCreator'
        - type: object
          properties:
            status:
              type: string
              enum:
                - ENABLED
                - DISABLED
            displayName:
              type: string
            email:
              type: string
              format: email
            phoneNumber:
              type: string
            userType:
              type: string
              enum:
                - DEVICE
                - INTERNAL
                - EXTERNAL
            externalId:
              type: string
            externalUsername:
              type: string
            expirationDate:
              type: string
              format: 'date-time'
          example:
            $ref: '#/components/examples/userCreator/value'
    userListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/user'
          example:
            type: userListResult
            limitExceeded: false
            size: 2
            users:
              - type: user
                id: AQ
                scopeId: AQ
                createdOn: '2019-09-10T15:08:54.781Z'
                createdBy: AQ
                modifiedOn: '2019-09-10T15:08:54.781Z'
                modifiedBy: AQ
                optlock: 0
                name: kapua-sys
                displayName: Kapua Sysadmin
                email: kapua-sys@eclipse.org
                phoneNumber: '+1 555 123 4567'
                status: ENABLED
                userType: INTERNAL
              - type: user
                id: Ag
                scopeId: AQ
                createdOn: '2019-09-10T15:08:54.781Z'
                createdBy: AQ
                modifiedOn: '2019-09-10T15:08:54.781Z'
                modifiedBy: AQ
                optlock: 0
                name: kapua-broker
                displayName: Kapua Broker
                email: kapua-broker@eclipse.org
                phoneNumber: '+1 555 123 4567'
                status: ENABLED
                userType: INTERNAL
    mfaOption:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaUpdatableEntity'
        - description: An object containing all the information for a single MfaOption
          type: object
          properties:
            userId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            trustKey:
              description: |
                The key of the trusted machine.
              type: string
            trustExpirationDate:
              description: |
                The moment when the machine trust will expire.
              type: string
              format: 'date-time'
          example:
            $ref: '#/components/examples/mfaOption/value'
    mfaOptionCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaUpdatableEntityCreator'
        - type: object
  examples:
    user:
      value:
        type: user
        id: AQ
        scopeId: AQ
        createdOn: '2019-09-10T15:08:54.781Z'
        createdBy: AQ
        modifiedOn: '2019-09-10T15:08:54.781Z'
        modifiedBy: AQ
        optlock: 0
        name: kapua-sys
        displayName: Kapua Sysadmin
        email: kapua-sys@eclipse.org
        phoneNumber: '+1 555 123 4567'
        status: ENABLED
        userType: INTERNAL
    userCreator:
      value:
        name: donald-duck
        status: ENABLED
        displayName: Donald Duck
        email: donald.duck@duckburg.org
        phoneNumber: '+1 (555) 816 1851'
        userType: INTERNAL
        expirationDate: '2019-12-31T00:00:00.000Z'
    mfaOption:
      value:
        type: mfaOption
        id: "Tu4UpgmN0A4"
        scopeId: "AQ"
        createdOn: "2021-05-12T08:04:21.962Z"
        createdBy: "AQ"
        modifiedOn: "2021-05-12T08:04:21.962Z"
        modifiedBy: "AQ"
        optlock: 1,
        userId: "AQ"
        trustKey: "exampleTrustKey"
        trustExpirationDate: '2020-31-12T00:00:00.000Z'
