openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Domains
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/domains/{domainId}:
    get:
      tags:
        - Domain
      summary: Get a single Domain
      operationId: domainGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './domain.yaml#/components/parameters/domainId'
      responses:
        200:
          description: The details of the desired Domain
          content:
            application/json:
              schema:
                $ref: './domain.yaml#/components/schemas/domain'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
