openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Service Configuration
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/serviceConfigurations/{componentId}:
    get:
      tags:
        - Service Configuration
      summary: Read a single Configuration
      operationId: serviceConfigurationRead
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './serviceConfiguration.yaml#/components/parameters/componentId'
      responses:
        200:
          description: The Configuration details of a single Service
          content:
            application/json:
              schema:
                $ref: './serviceConfiguration.yaml#/components/schemas/componentConfigurations'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    put:
      tags:
        - Service Configuration
      summary: Update a single Configuration
      operationId: serviceConfigurationWrite
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './serviceConfiguration.yaml#/components/parameters/componentId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './serviceConfiguration.yaml#/components/schemas/componentConfigurationInput'
        required: true
      responses:
        200:
          description: Updates the Configuration details of a single Service
          content:
            application/json:
              schema:
                $ref: './serviceConfiguration.yaml#/components/schemas/componentConfiguration'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
