openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Device Management - Operations
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/operations/{operationId}:
    get:
      tags:
        - Device Management - Operation
      summary: Get a single Device Registry Operation
      operationId: deviceRegistryOperationGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: './deviceOperation.yaml#/components/parameters/operationId'
      responses:
        200:
          description: The details of the desired Registry Operation
          content:
            application/json:
              schema:
                $ref: './deviceOperation.yaml#/components/schemas/deviceOperation'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - Device Management - Operation
      summary: Delete a single Registry Operation
      operationId: deviceRegistryOperationDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: './deviceOperation.yaml#/components/parameters/operationId'
      responses:
        204:
          description: The Registry Operation has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
