openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Credentials
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/credentials/_query:
    post:
      tags:
        - Credential
      summary: Query the Credentials
      operationId: credentialQuery
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        $ref: '../openapi.yaml#/components/requestBodies/kapuaQuery'
      responses:
        200:
          description: The result of the query
          content:
            application/json:
              schema:
                $ref: './credential.yaml#/components/schemas/credentialListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
