openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Credentials
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  parameters:
    credentialId:
      name: credentialId
      in: path
      description: The ID of the Credential on which to perform the operation
      schema:
        $ref: '../openapi.yaml#/components/schemas/kapuaId'
      required: true
  schemas:
    credential:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaUpdatableEntity'
        - description: An object containing all the information for a single Credential
          type: object
          properties:
            userId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            credentialType:
              type: string
              enum:
                - PASSWORD
                - API_KEY
                - JWT
            credentialKey:
              type: string
            status:
              type: string
              enum:
                - ENABLED
                - DISABLED
            expirationDate:
              type: string
              format: 'date-time'
            loginFailures:
              description: |
                A count of how many times an user failed to login with this Credential.
                This field is cleared after a successful login
              type: integer
            firstLoginFailure:
              description: |
                The moment when the first login failure has been recorded with this credential.
                This field is cleared after a successful login
              type: string
              format: 'date-time'
            loginFailuresReset:
              description: |
                The moment when the failure attempts for this Credential will be reset.
                This field is cleared after a successful login
              type: string
              format: 'date-time'
            lockoutReset:
              description: |
                The moment when this Credential will be enabled again after a lockout due to too many failures.
                This field is cleared after a successful login
              type: string
              format: 'date-time'
    credentialCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaUpdatableEntityCreator'
        - type: object
          properties:
            userId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            credentialType:
              type: string
              enum:
                - PASSWORD
                - API_KEY
                - JWT
            credentialKey:
              type: string
            credentialStatus:
              type: string
              enum:
                - ENABLED
                - DISABLED
            expirationDate:
              type: string
              format: 'date-time'
          example:
            userId: "AQ"
            credentialType: PASSWORD
            credentialKey: "new-password-123!"
            credentialStatus: ENABLED
            expirationDate: "2019-12-31T00:00:00.000Z"
    credentialListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/credential'
