openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Device Management - Package
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  schemas:
    devicePackage:
      type: object
      description: A Device Package
      properties:
        name:
          type: string
        version:
          type: string
        bundleInfos:
          type: object
          properties:
            bundleInfo:
              type: array
              items:
                $ref: '#/components/schemas/bundleInfo'
        installDate:
          type: string
          format: 'date-time'
      example:
        name: org.eclipse.kura.demo.heater
        version: 1.0.300
        bundleInfos:
          bundleInfo:
            - name: org.eclipse.kura.demo.heater
              version: 1.0.300
    devicePackages:
      type: object
      properties:
        devicePackage:
          type: array
          items:
            $ref: '#/components/schemas/devicePackage'
      example:
        type: devicePackages
        devicePackage:
          - name: org.eclipse.kura.demo.heater
            version: 1.0.300
            bundleInfos:
              bundleInfo:
                - name: org.eclipse.kura.demo.heater
                  version: 1.0.300
    devicePackageDownloadRequest:
      type: object
      properties:
        uri:
          type: string
        name:
          type: string
        version:
          type: string
        username:
          type: string
        password:
          type: string
        fileHash:
          type: string
        fileType:
          type: string
        install:
          type: boolean
        reboot:
          type: boolean
        rebootDelay:
          type: integer
        advancedOptions:
          type: object
          properties:
            restart:
              type: boolean
            blockSize:
              type: integer
            blockDelay:
              type: integer
            blockTimeout:
              type: integer
            notifyBlockSize:
              type: integer
            installVerifyURI:
              type: string
      example:
        uri: https://download.eclipse.org/kura/releases/4.1.0/org.eclipse.kura.demo.heater_1.0.500.dp
        name: heater
        version: 1.0.500
        username: username
        password: password
        fileHash: MD5:0d04154164145cd6b2167fdd457ed28f
        fileType: DEPLOYMENT_PACKAGE
        install: true
        reboot: false
        rebootDelay: 0
        advancedOptions:
          restart: false
          blockSize: 128
          blockDelay: 0
          blockTimeout: 5000
          notifyBlockSize: 256
          installVerifyURI: https://download.eclipse.org/kura/releases/4.1.0/org.eclipse.kura.demo.heater_1.0.500.verifier.sh
    bundleInfo:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
