openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Package
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/packages/_uninstall:
    post:
      tags:
        - Device Management - Package
      summary: Uninstall a Package
      operationId: devicePackageUninstall
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                version:
                  type: string
                reboot:
                  type: boolean
                rebootDelay:
                  type: integer
              required:
                - name
                - version
            example:
              name: org.eclipse.kura.demo.heater
              version: 1.0.500
        required: true
      responses:
        200:
          description: The corresponding Device Management Operation to track the progress of the Device Package Uninstall Request
          content:
            application/json:
              schema:
                $ref: '../deviceOperation/deviceOperation.yaml#/components/schemas/deviceOperation'
        204:
          description: |
            The Package Install request has been successfully received. However, this does NOT mean that the package has been successfully installed, since the Package Install
            is an asynchronous operation and may still be in progress. APIs are available at `device/{deviceId}/operations` and `device/{deviceId}/operations/{operationId}/notifications`
            to track asynchronous operations.
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
