openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Access Infos
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/accessinfos/{accessInfoId}/permissions/_query:
    post:
      tags:
        - Access Permission
      summary: Query the AccessPermissions
      operationId: accessPermissionQuery
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './accessInfo.yaml#/components/parameters/accessInfoId'
      requestBody:
        $ref: '../openapi.yaml#/components/requestBodies/kapuaQuery'
      responses:
        200:
          description: The result of the query
          content:
            application/json:
              schema:
                $ref: './accessInfo.yaml#/components/schemas/accessPermissionListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
