openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs - Targets
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobs/{jobId}/targets/{targetId}:
    get:
      tags:
        - Job - Target
      summary: Get a single Job Target
      operationId: jobTargetGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
        - $ref: './jobTarget.yaml#/components/parameters/targetId'
      responses:
        200:
          description: The details of the desired Job Target
          content:
            application/json:
              schema:
                $ref: './jobTarget.yaml#/components/schemas/jobTarget'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - Job - Target
      summary: Delete a single Job Target
      operationId: jobTargetDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
        - $ref: './jobTarget.yaml#/components/parameters/targetId'
      responses:
        204:
          description: The Job Target has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
