openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Device Event
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/events:
    get:
      tags:
        - Device Event
      summary: Get all the DeviceEvents
      operationId: deviceEventList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - name: resource
          in: query
          description: The resource of the DeviceEvent in which to search results
          schema:
            type: string
        - description: The start date to filter the results.
          name: startDate
          in: query
          schema:
            type: string
            format: 'date-time'
        - description: The end date to filter the results.
          name: endDate
          in: query
          schema:
            type: string
            format: 'date-time'
        - $ref: '../openapi.yaml#/components/parameters/sortParam'
        - $ref: '../openapi.yaml#/components/parameters/sortDir'
        - $ref: '../openapi.yaml#/components/parameters/askTotalCount'
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
      responses:
        200:
          description: The list of the Device Events available in the Scope
          content:
            application/json:
              schema:
                $ref: './deviceEvent.yaml#/components/schemas/deviceEventListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
