openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Groups
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  parameters:
    groupId:
      name: groupId
      in: path
      description: The ID of the Group on which to perform the operation
      schema:
        $ref: '../openapi.yaml#/components/schemas/kapuaId'
      required: true
  schemas:
    group:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntity'
        - type: object
          example:
            type: group
            id: Skm7PvmgOh0
            scopeId: AQ
            createdOn: '2019-09-13T15:16:09.174Z'
            createdBy: AQ
            modifiedOn: '2019-09-13T15:16:09.174Z'
            modifiedBy: AQ
            optlock: 1
            name: group-1
            description: An Access Group
    groupCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntityCreator'
        - type: object
          example:
            name: group-1
            description: An Access Group
    groupListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/group'
          example:
            type: groupListResult
            limitExceeded: false
            size: 1
            items:
              - type: group
                id: Skm7PvmgOh0
                scopeId: AQ
                createdOn: '2019-09-13T15:16:09.174Z'
                createdBy: AQ
                modifiedOn: '2019-09-13T15:16:09.174Z'
                modifiedBy: AQ
                optlock: 1
                name: group-1
                description: An Access Group
