openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Data Message
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/data/messages/{datastoreMessageId}:
    get:
      tags:
        - Data Message
      summary: Get a single DataMessage
      operationId: dataMessageGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: './dataMessage.yaml#/components/parameters/datastoreMessageId'
      responses:
        200:
          description: The desired DataMessage
          content:
            application/json:
              schema:
                $ref: './dataMessage.yaml#/components/schemas/dataMessageListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
