openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Connection
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/deviceconnections:
    get:
      tags:
        - Device Connection
      summary: Get all the Connections
      operationId: connectionList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/clientId'
        - $ref: './deviceConnection.yaml#/components/parameters/connectionStatus'
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
      responses:
        200:
          description: The list of the Connections available in the Scope
          content:
            application/json:
              schema:
                $ref: './deviceConnection.yaml#/components/schemas/connectionListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
