openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Keystore
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/keystore:
    get:
      tags:
        - Device Management - Keystore
      summary: Get the keystores list from a single Device
      operationId: deviceKeystoresGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      responses:
        200:
          description: The keystores list from the Device
          content:
            application/json:
              schema:
                $ref: './deviceKeystore.yaml#/components/schemas/deviceKeystores'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
  /{scopeId}/devices/{deviceId}/keystore/items:
    get:
      tags:
        - Device Management - Keystore
      summary: Get the keystore items from a single Device
      operationId: deviceKeystoreItemsGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - name: keystoreId
          in: query
          description: The keystore id to filter the results.
          schema:
            type: string
        - name: alias
          in: query
          description: The alias to filter the results.
          schema:
            type: string
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      responses:
        200:
          description: The keystore items from the Device
          content:
            application/json:
              schema:
                $ref: './deviceKeystore.yaml#/components/schemas/deviceKeystoreItems'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
  /{scopeId}/devices/{deviceId}/keystore/item:
    get:
      tags:
        - Device Management - Keystore
      summary: Get a keystore item from a single Device
      operationId: deviceKeystoreItemGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - name: keystoreId
          in: query
          description: The keystore id to filter the results.
          required: true
          schema:
            type: string
        - name: alias
          in: query
          description: The alias to filter the results.
          required: true
          schema:
            type: string
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      responses:
        200:
          description: The keystore item from the Device
          content:
            application/json:
              schema:
                $ref: './deviceKeystore.yaml#/components/schemas/deviceKeystoreItem'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - Device Management - Keystore
      summary: Delete a keystore item from a single Device
      operationId: deviceKeystoreItemDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - name: keystoreId
          in: query
          description: The keystore id of the item to delete.
          required: true
          schema:
            type: string
        - name: alias
          in: query
          description: The alias of the item to delete.
          required: true
          schema:
            type: string
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      responses:
        204:
          description: The keystore item has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
  /{scopeId}/devices/{deviceId}/keystore/items/certificateInfo:
    post:
      tags:
        - Device Management - Keystore
      summary: Creates a certificate from the Certificate Info Servuce in a Device
      operationId: deviceKeystoreCertificateInfoCreate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './deviceKeystore.yaml#/components/schemas/deviceKeystoreCertificateInfo'
      responses:
        204:
          description: The certificate has been created into the device keystore
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
  /{scopeId}/devices/{deviceId}/keystore/items/certificateRaw:
    post:
      tags:
        - Device Management - Keystore
      summary: Creates a certificate in a Device
      operationId: deviceKeystoreCertificateRawCreate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './deviceKeystore.yaml#/components/schemas/deviceKeystoreCertificate'
      responses:
        204:
          description: The certificate has been created into the device keystore
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
  /{scopeId}/devices/{deviceId}/keystore/items/keypair:
    post:
      tags:
        - Device Management - Keystore
      summary: Creates a key pair in a Device
      operationId: deviceKeystoreKeypairCreate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './deviceKeystore.yaml#/components/schemas/deviceKeystoreKeypair'
      responses:
        204:
          description: The keypair has been created into the device keystore
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
  /{scopeId}/devices/{deviceId}/keystore/items/csr:
    post:
      tags:
        - Device Management - Keystore
      summary: Request a certificate signing request from a Device
      operationId: deviceKeystoreCSR
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './deviceKeystore.yaml#/components/schemas/deviceKeystoreCSRInfo'
      responses:
        204:
          description: The certificate signing request has been returned.
          content:
            application/json:
              schema:
                $ref: './deviceKeystore.yaml#/components/schemas/deviceKeystoreCSR'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
