version: '3.1'

services:
  keycloak:
    container_name: kapua-keycloak
    image: kapua/kapua-keycloak:${IMAGE_VERSION}
    ports:
      - "9090:8080"
      - "9443:8443"
    volumes:
      - "../../target/compose/sso/certs:/etc/x509/https"
    environment:
      - KAPUA_CONSOLE_URL
      - KEYCLOAK_ADMIN_USER
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
