openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Device Management - Snapshot
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/snapshots/{snapshotId}/_rollback:
    post:
      tags:
        - Device Management - Snapshot
      summary: Rollback to Snapshot
      operationId: deviceSnapshotRollback
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: './deviceSnapshot.yaml#/components/parameters/snapshotId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      responses:
        204:
          description: The Snapshot has been applied
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
